export const DEMO_DOCS = [
  {
    filename: 'demo_api_spec_v1.md',
    content: [
      '# API Reference — Payments Platform v1.2',
      '',
      '## Authentication',
      'All API requests require a Bearer token in the Authorization header.',
      'Tokens expire after **60 minutes** and must be refreshed using the /auth/refresh endpoint.',
      '',
      '## Rate Limits',
      'The API enforces the following rate limits per API key:',
      '',
      '- Standard tier: **500 requests per minute**',
      '- Premium tier: **2,000 requests per minute**',
      '- Burst allowance: up to 200% of tier limit for 10 seconds',
      '',
      'Exceeding the rate limit returns HTTP 429. Clients should back off for **30 seconds** before retrying.',
      '',
      '## Pagination',
      'All list endpoints use cursor-based pagination. The default page size is **50 records**.',
      'Maximum page size is **200 records**.',
      '',
      '## Webhooks',
      'Webhook payloads are signed using HMAC-SHA256.',
      'Signatures expire after **5 minutes** of the event timestamp.',
    ].join('\n'),
  },
  {
    filename: 'demo_runbook_v1.md',
    content: [
      '# Engineering Runbook — Payments Platform',
      '',
      '## Overview',
      'This runbook covers operational procedures for the Payments Platform backend.',
      '',
      '## Authentication Notes',
      'Tokens are valid for **24 hours** in production. The 60-minute figure in the API docs',
      'is outdated and refers to the legacy v1.0 system. Do not refresh tokens unless they',
      'are actually expired.',
      '',
      '## Rate Limit Handling',
      'Production rate limits are configured as follows:',
      '',
      '- Standard tier: **1,000 requests per minute**',
      '- Premium tier: **5,000 requests per minute**',
      '',
      'When a client hits 429, the Retry-After header specifies the exact wait time.',
      'Default backoff in the load balancer config is set to **60 seconds**, not 30.',
      '',
      '## Pagination',
      'Internal services use a page size of **100 records** as the default.',
      'The 50-record default in the API spec applies to external clients only.',
      '',
      '## Incident Response',
      'For rate limit incidents, check the Redis cache for key exhaustion before',
      'assuming a traffic spike. See runbook section 4.2 for escalation path.',
    ].join('\n'),
  },
  {
    filename: 'demo_sdk_docs_v2.md',
    content: [
      '# Python SDK Documentation — v2.1',
      '',
      '## Installation',
      '```',
      'pip install payments-sdk==2.1.0',
      '```',
      '',
      '## Initialization',
      '```python',
      'from payments_sdk import PaymentsClient',
      '',
      'client = PaymentsClient(',
      '    api_key="your_api_key",',
      '    timeout=30,',
      '    max_retries=3',
      ')',
      '```',
      '',
      '## Creating a Payment',
      '```python',
      'payment = client.payments.create(',
      '    amount=1000,',
      '    currency="usd",',
      '    customer_id="cust_123"',
      ')',
      '```',
      '',
      '## Error Handling',
      'The SDK raises `PaymentsError` for all API errors.',
      'Use `error.code` to identify the error type.',
      'Transient errors (429, 500, 503) are automatically retried up to **3 times**',
      'with exponential backoff starting at **1 second**.',
      '',
      '## Supported Payment Methods',
      '- Credit card',
      '- ACH bank transfer',
      '- Wire transfer',
    ].join('\n'),
  },
]

export const PRESET_QUESTIONS = [
  'What is the rate limit for the standard tier?',
  'How many times does the SDK retry a failed request?',
  'How long before API tokens expire?',
]
