export const DEMO_DOCS = [
  {
    filename: 'demo_api_spec_v1.md',
    content: [
      '# Payments API - REST Specification v1.2',
      '',
      '## Overview',
      'The Payments API provides programmatic access to the payments platform. All requests must be authenticated using a Bearer token.',
      '',
      '## Authentication',
      'All API calls require a Bearer token in the Authorization header.',
      '',
      '## Rate Limits',
      '',
      'Rate limits are enforced per API key. Exceeding the limit returns HTTP 429.',
      '',
      'Tier limits:',
      '- Standard: 100 requests per minute (burst allowance: 150)',
      '- Professional: 300 requests per minute (burst allowance: 450)',
      '- Enterprise: Unlimited',
      '',
      'Standard tier accounts are limited to 100 requests per minute. Customers who exceed this limit consistently should be upgraded to the Professional tier.',
      '',
      '## Endpoints',
      '',
      'POST /v1/payments - Create a new payment transaction',
      'GET /v1/payments/{id} - Retrieve a payment by ID',
      'GET /v1/payments - List payments with cursor-based pagination',
      '',
      '## Error Codes',
      '- 400: Bad Request - invalid parameters',
      '- 401: Unauthorized - invalid or missing API key',
      '- 429: Too Many Requests - rate limit exceeded',
      '- 500: Internal Server Error',
    ].join('\n'),
  },
  {
    filename: 'demo_runbook_v1.md',
    content: [
      '# Payments Platform - Operations Runbook v1.0',
      '',
      '## Deployment',
      'Deploy via CI/CD pipeline. Production deployments require approval from two engineers.',
      '',
      '## Monitoring',
      '- Latency dashboard: grafana.internal/payments',
      '- Alert threshold: P95 latency above 500ms triggers oncall page',
      '',
      '## Incident Response',
      '',
      '### Rate Limit Spikes',
      'If a customer reports 429 errors, check their rate limit tier in the admin console.',
      'Standard tier limit: 100 requests per minute. If the customer legitimately exceeds this, initiate a tier upgrade.',
      '',
      '### Retry Policy',
      'Production systems retry failed requests up to 5 times with exponential backoff starting at 2 seconds.',
      '',
      '### Payment Failures',
      '1. Check the payment provider status page',
      '2. Review error logs for specific error codes',
      '3. Contact payment provider support if the issue is systemic',
      '',
      '## Escalation Contacts',
      '- Primary oncall: payments-oncall@internal',
      '- Escalation: platform-leads@internal',
      '',
      '## Runbook Maintenance',
      'Reviewed quarterly. Last reviewed: Q4 2024.',
    ].join('\n'),
  },
  {
    filename: 'demo_sdk_docs_v2.md',
    content: [
      '# DocSense SDK - Developer Guide v2.4',
      '',
      '## Installation',
      'Install the SDK: pip install docsense-sdk==2.4.0',
      '',
      '## Initialization',
      'Import and initialize the client with your API key.',
      '',
      '## Retry Policy',
      'The SDK retries failed requests up to 3 times with exponential backoff starting at 1 second.',
      '',
      'Default retry configuration for SDK v2:',
      '- Max retries: 3',
      '- Initial delay: 1000ms',
      '- Backoff multiplier: 2x',
      '- Maximum delay: 8000ms',
      '',
      'A request that fails 3 consecutive times raises MaxRetriesExceeded. Set max_retries=0 to disable retry behavior entirely.',
      '',
      '## Timeout Configuration',
      'Default request timeout is 30 seconds. Override by passing a timeout parameter to the client constructor.',
      '',
      '## Error Handling',
      'Catch MaxRetriesExceeded when the request fails after exhausting all 3 retry attempts.',
      'Catch AuthError for invalid or expired API key errors.',
    ].join('\n'),
  },
]

export const PRESET_QUESTIONS = [
  'What is the rate limit for the standard tier?',
  'How many times does the SDK retry a failed request?',
  'How long is customer PII retained after account closure?',
]
