export const DEMO_DOCS = [
  {
    filename: 'demo_api_spec_v1.md',
    content: [
      '# Payments API - REST Specification v1.2',
      '',
      '## Overview',
      'The Payments API provides programmatic access to the payments platform. All requests must be authenticated using a Bearer token.',
      '',
      '## Authentication',
      'All API calls require a Bearer token in the Authorization header.',
      '',
      '## Rate Limits',
      '',
      'Rate limits are enforced per API key. Exceeding the limit returns HTTP 429.',
      '',
      'Tier limits:',
      '- Standard: 100 requests per minute (burst allowance: 150)',
      '- Professional: 300 requests per minute (burst allowance: 450)',
      '- Enterprise: Unlimited',
      '',
      'Standard tier accounts are limited to 100 requests per minute. Customers who exceed this limit consistently should be upgraded to the Professional tier.',
      '',
      '## Endpoints',
      '',
      'POST /v1/payments - Create a new payment transaction',
      'GET /v1/payments/{id} - Retrieve a payment by ID',
      'GET /v1/payments - List payments with cursor-based pagination',
      '',
      '## Error Codes',
      '- 400: Bad Request - invalid parameters',
      '- 401: Unauthorized - invalid or missing API key',
      '- 429: Too Many Requests - rate limit exceeded',
      '- 500: Internal Server Error',
    ].join('\n'),
  },
  {
    filename: 'demo_runbook_v1.md',
    content: [
      '# Payments Platform - Operations Runbook v1.0',
      '',
      '## Deployment',
      'Deploy via CI/CD pipeline. Production deployments require approval from two engineers.',
      '',
      '## Monitoring',
      '- Latency dashboard: grafana.internal/payments',
      '- Alert threshold: P95 latency above 500ms triggers oncall page',
      '',
      '## Incident Response',
      '',
      '### Rate Limit Spikes',
      'If a customer reports 429 errors, check their rate limit tier in the admin console.',
      'Standard tier limit: 100 requests per minute. If the customer legitimately exceeds this, initiate a tier upgrade.',
      '',
      '### Payment Failures',
      '1. Check the payment provider status page',
      '2. Review error logs for specific error codes',
      '3. Contact payment provider support if the issue is systemic',
      '',
      '## Escalation Contacts',
      '- Primary oncall: payments-oncall@internal',
      '- Escalation: platform-leads@internal',
      '',
      '## Runbook Maintenance',
      'Reviewed quarterly. Last reviewed: Q4 2024.',
    ].join('\n'),
  },
  {
    filename: 'demo_sdk_docs_v2.md',
    content: [
      '# DocSense SDK - Developer Guide v2.4',
      '',
      '## Installation',
      'Install the SDK: pip install docsense-sdk==2.4.0',
      '',
      '## Initialization',
      'Import and initialize the client with your API key.',
      '',
      '## Retry Policy',
      'The SDK automatically retries failed requests using exponential backoff.',
      '',
      'Default retry configuration for SDK v2:',
      '- Max retries: 3',
      '- Initial delay: 500ms',
      '- Backoff multiplier: 2x',
      '- Maximum delay: 8000ms',
      '',
      'A request that fails 3 consecutive times raises MaxRetriesExceeded. Set max_retries=0 to disable retry behavior entirely.',
      '',
      '## Timeout Configuration',
      'Default request timeout is 30 seconds. Override by passing a timeout parameter to the client constructor.',
      '',
      '## Error Handling',
      'Catch MaxRetriesExceeded when the request fails after exhausting all 3 retry attempts.',
      'Catch AuthError for invalid or expired API key errors.',
    ].join('\n'),
  },
  {
    filename: 'demo_sdk_docs_v3.md',
    content: [
      '# DocSense SDK - Developer Guide v3.1',
      '',
      '## Installation',
      'Install the SDK: pip install docsense-sdk==3.1.0',
      '',
      "## What's New in v3",
      '- Async support via DocSenseAsyncClient',
      '- Streaming responses via query_stream',
      '- Updated retry policy with increased resilience',
      '',
      '## Retry Policy',
      'The SDK retries failed requests with exponential backoff.',
      '',
      'Default retry configuration for SDK v3:',
      '- Max retries: 5',
      '- Initial delay: 250ms',
      '- Backoff multiplier: 2x',
      '- Maximum delay: 16000ms',
      '',
      'The retry count was increased from 3 to 5 in v3.0 to improve resilience against transient network failures. A request that fails all 5 retries raises MaxRetriesExceeded.',
      '',
      '## Timeout Configuration',
      'Default request timeout is 30 seconds. Configurable via the timeout parameter on the client constructor.',
      '',
      '## Streaming',
      'Use query_stream to receive a streaming response, yielding text chunks as they arrive from the API.',
    ].join('\n'),
  },
  {
    filename: 'demo_security_policy.md',
    content: [
      '# Information Security Policy - Data Retention v2.1',
      '',
      '## Scope',
      'This policy applies to all customer data processed by the platform, including personally identifiable information (PII).',
      '',
      '## Data Retention Periods',
      '',
      '### Active Account Data',
      'Customer data is retained for the lifetime of the account plus the post-closure retention period defined below.',
      '',
      '### Post-Closure Retention',
      'Upon account closure, customer PII is retained for 30 days to support:',
      '- Final billing dispute resolution',
      '- Regulatory audit requests submitted within the window',
      '- Active fraud investigations',
      '',
      'After 30 days, all PII is permanently deleted from production systems. Backup media is purged on the next scheduled rotation, within 7 days of the 30-day mark.',
      '',
      '## PII Categories Covered',
      '- Name, email address, phone number',
      '- Payment method tokens',
      '- Usage logs containing identifiable information',
      '',
      '## Exceptions',
      'Legal hold requests override standard retention periods. Contact the legal team before deleting any data subject to a legal hold.',
      '',
      '## Policy Owner',
      'Security Engineering. Reviewed annually. Last reviewed: January 2025.',
    ].join('\n'),
  },
  {
    filename: 'demo_compliance_doc.md',
    content: [
      '# Compliance Framework - Data Handling Requirements v1.3',
      '',
      '## Regulatory Scope',
      'This document covers data handling obligations under applicable privacy regulations including GDPR Article 17 and CCPA.',
      '',
      '## Data Subject Rights',
      '',
      '### Right to Erasure',
      'Customers may request deletion of their personal data. Erasure requests are processed within 30 days of submission.',
      '',
      '### Data Portability',
      'Customers may export their data at any time during active account tenure.',
      '',
      '## Retention Requirements',
      '',
      '### Post-Account-Closure Retention',
      'Customer PII must be retained for a minimum of 90 days following account closure to satisfy regulatory audit obligations and dispute resolution requirements under applicable financial services regulations.',
      '',
      'This 90-day requirement supersedes shorter internal retention periods specified in other policy documents. Financial regulators require 90 days of record retention following account closure.',
      '',
      'After 90 days, PII is deleted in accordance with data erasure procedures.',
      '',
      '## Audit Trail',
      'All data deletion events are logged with timestamp, data category, and authorizing system. Deletion logs are retained for 7 years.',
      '',
      '## Compliance Owner',
      'Legal and Compliance team. Reviewed annually. Last reviewed: March 2025.',
    ].join('\n'),
  },
]

export const PRESET_QUESTIONS = [
  'What is the rate limit for the standard tier?',
  'How many times does the SDK retry a failed request?',
  'How long is customer PII retained after account closure?',
]
